import { useEffect, useState } from "react";
import { Navigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import type { SystemReport, SystemReportType } from "@/types";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { toast } from "sonner";
import { FileDown, Sparkles, Loader2 } from "lucide-react";

const TYPE_LABEL: Record<SystemReportType, string> = {
  monthly: "Monthly",
  quarterly: "Quarterly",
  biannual: "Biannual",
  annual: "Annual",
};

export default function SystemReportsPage() {
  const { isManager, roleLoaded, companyId } = useAuth();
  const [items, setItems] = useState<SystemReport[]>([]);
  const [loading, setLoading] = useState(true);
  const [requesting, setRequesting] = useState(false);
  const [reqType, setReqType] = useState<SystemReportType>("monthly");

  const refresh = async () => {
    if (!companyId) return;
    const { data } = await supabase
      .from("system_reports")
      .select("*")
      .eq("company_id", companyId)
      .order("created_at", { ascending: false });
    setItems((data as SystemReport[]) ?? []);
    setLoading(false);
  };

  useEffect(() => {
    refresh();
    if (!companyId) return;
    const ch = supabase
      .channel(`sysreports-${companyId}`)
      .on(
        "postgres_changes",
        { event: "*", schema: "public", table: "system_reports", filter: `company_id=eq.${companyId}` },
        () => refresh(),
      )
      .subscribe();
    return () => {
      supabase.removeChannel(ch);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [companyId]);

  const generate = async () => {
    setRequesting(true);
    try {
      const { error } = await supabase.functions.invoke("trigger-ai-report", {
        body: { report_type: reqType },
      });
      if (error) throw error;
      toast.success("AI report requested — n8n will post it back when ready");
      refresh();
    } catch (e: any) {
      toast.error(e.message ?? "Failed to request");
    } finally {
      setRequesting(false);
    }
  };

  if (roleLoaded && !isManager) return <Navigate to="/" replace />;

  return (
    <div className="space-y-6 sm:pl-64">
      <header className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">AI reports</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Generated by n8n on the 1st of every month — and on demand.
          </p>
        </div>
        <div className="flex items-end gap-2">
          <Select value={reqType} onValueChange={(v) => setReqType(v as SystemReportType)}>
            <SelectTrigger className="w-[160px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {(Object.keys(TYPE_LABEL) as SystemReportType[]).map((k) => (
                <SelectItem key={k} value={k}>
                  {TYPE_LABEL[k]}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Button onClick={generate} disabled={requesting} className="gap-2">
            {requesting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
            Request
          </Button>
        </div>
      </header>

      {loading ? (
        <div className="rounded-2xl border border-border bg-surface-elevated p-6 text-center text-sm text-muted-foreground">
          Loading…
        </div>
      ) : items.length === 0 ? (
        <div className="rounded-2xl border border-dashed border-border bg-surface-elevated p-10 text-center">
          <Sparkles className="mx-auto h-8 w-8 text-muted-foreground" />
          <p className="mt-2 text-sm font-semibold">No reports yet</p>
          <p className="text-xs text-muted-foreground">
            Click "Request" to generate one — or wait for the monthly cron.
          </p>
        </div>
      ) : (
        <div className="grid gap-3 md:grid-cols-2">
          {items.map((r) => (
            <Card key={r.id} className="shadow-elevation-1">
              <CardContent className="space-y-3 p-4">
                <div className="flex items-center justify-between gap-2">
                  <div>
                    <div className="text-xs uppercase tracking-wide text-muted-foreground">
                      {TYPE_LABEL[r.report_type]}
                    </div>
                    <div className="font-semibold">
                      {r.title ?? `${r.period_start} → ${r.period_end}`}
                    </div>
                  </div>
                  <Badge
                    variant={r.status === "ready" ? "default" : r.status === "failed" ? "destructive" : "secondary"}
                  >
                    {r.status}
                  </Badge>
                </div>
                <div className="text-xs text-muted-foreground">
                  {r.period_start} → {r.period_end}
                  {r.generated_at && (
                    <> · generated {new Date(r.generated_at).toLocaleDateString()}</>
                  )}
                </div>
                {r.file_url ? (
                  <Button asChild className="w-full gap-2">
                    <a href={r.file_url} target="_blank" rel="noopener noreferrer">
                      <FileDown className="h-4 w-4" /> Download
                    </a>
                  </Button>
                ) : (
                  <div className="rounded-lg bg-secondary p-2 text-center text-xs text-muted-foreground">
                    Waiting for n8n to post the file…
                  </div>
                )}
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
